export default {
  ADD_DATE: 'ADD_DATE',
  TOGGLE_SPINNER: 'TOGGLE_SPINNER',
  ADD_PICTURE: 'ADD_PICTURE',
  ADD_ERROR: 'ADD_ERROR',
  SET_CURR_PICTURE: 'SET_CURR_PICTURE',
  ADD_FAVORITE: 'ADD_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  CLEAR_FAVORITES: 'CLEAR_FAVORITES',
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
};
